# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:40:04+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field, RootModel


class Play(BaseModel):
    AssistedByPlayerID: Optional[int] = None
    AwayPlayerID: Optional[int] = None
    AwayTeamScore: Optional[int] = None
    BaselineOffsetPercentage: Optional[float] = None
    BlockedByPlayerID: Optional[int] = None
    Category: Optional[str] = None
    Coordinates: Optional[str] = None
    Created: Optional[str] = None
    Description: Optional[str] = None
    FastBreak: Optional[bool] = None
    HomePlayerID: Optional[int] = None
    HomeTeamScore: Optional[int] = None
    Opponent: Optional[str] = None
    OpponentID: Optional[int] = None
    PlayID: Optional[int] = None
    PlayerID: Optional[int] = None
    Points: Optional[int] = None
    PotentialPoints: Optional[int] = None
    QuarterID: Optional[int] = None
    QuarterName: Optional[str] = None
    ReceivingPlayerID: Optional[int] = None
    ReceivingTeam: Optional[str] = None
    ReceivingTeamID: Optional[int] = None
    Sequence: Optional[int] = None
    ShotMade: Optional[bool] = None
    SideOfBasket: Optional[str] = None
    SidelineOffsetPercentage: Optional[float] = None
    StolenByPlayerID: Optional[int] = None
    SubstituteInPlayerID: Optional[int] = None
    SubstituteOutPlayerID: Optional[int] = None
    Team: Optional[str] = None
    TeamID: Optional[int] = None
    TimeRemainingMinutes: Optional[int] = None
    TimeRemainingSeconds: Optional[int] = None
    Type: Optional[str] = None
    Updated: Optional[str] = None


class Quarter(BaseModel):
    AwayScore: Optional[int] = None
    GameID: Optional[int] = None
    HomeScore: Optional[int] = None
    Name: Optional[str] = None
    Number: Optional[int] = None
    QuarterID: Optional[int] = None


class Series(BaseModel):
    AwayTeamWins: Optional[int] = None
    GameNumber: Optional[int] = None
    HomeTeamWins: Optional[int] = None
    MaxLength: Optional[int] = None


class Format(Enum):
    XML = 'XML'
    JSON = 'JSON'


class Game(BaseModel):
    AlternateID: Optional[int] = None
    Attendance: Optional[int] = None
    AwayRotationNumber: Optional[int] = None
    AwayTeam: Optional[str] = None
    AwayTeamID: Optional[int] = None
    AwayTeamMoneyLine: Optional[int] = None
    AwayTeamScore: Optional[int] = None
    Channel: Optional[str] = None
    CrewChiefID: Optional[int] = None
    DateTime: Optional[str] = None
    DateTimeUTC: Optional[str] = None
    Day: Optional[str] = None
    GameEndDateTime: Optional[str] = None
    GameID: Optional[int] = None
    GlobalAwayTeamID: Optional[int] = None
    GlobalGameID: Optional[int] = None
    GlobalHomeTeamID: Optional[int] = None
    HomeRotationNumber: Optional[int] = None
    HomeTeam: Optional[str] = None
    HomeTeamID: Optional[int] = None
    HomeTeamMoneyLine: Optional[int] = None
    HomeTeamScore: Optional[int] = None
    IsClosed: Optional[bool] = None
    LastPlay: Optional[str] = None
    NeutralVenue: Optional[bool] = None
    OverPayout: Optional[int] = None
    OverUnder: Optional[float] = None
    PointSpread: Optional[float] = None
    PointSpreadAwayTeamMoneyLine: Optional[int] = None
    PointSpreadHomeTeamMoneyLine: Optional[int] = None
    Quarter: Optional[str] = None
    Quarters: Optional[List[Quarter]] = None
    RefereeID: Optional[int] = None
    Season: Optional[int] = None
    SeasonType: Optional[int] = None
    SeriesInfo: Optional[Series] = None
    StadiumID: Optional[int] = None
    Status: Optional[str] = None
    TimeRemainingMinutes: Optional[int] = None
    TimeRemainingSeconds: Optional[int] = None
    UmpireID: Optional[int] = None
    UnderPayout: Optional[int] = None
    Updated: Optional[str] = None


class PlayByPlay(BaseModel):
    Game_1: Optional[Game] = Field(None, alias='Game')
    Plays: Optional[List[Play]] = None
    Quarters: Optional[List[Quarter]] = None


class FieldFormatPlayByPlayDeltaDateMinutesGetResponse(RootModel[List[PlayByPlay]]):
    root: List[PlayByPlay]
